/// Flutter icons Sicons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Sicons
///      fonts:
///       - asset: fonts/Sicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Sicons {
  Sicons._();

  static const _kFontFam = 'Sicons';
  static const String? _kFontPkg = null;

  static const IconData like = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_2 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
